language: ruby

services:
  - docker

before_install:
  - docker build -t chordpro .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chordpro
